from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from fastapi.responses import Response
from services.groq_service import get_pronunciation_guide, PronunciationGuideResponse
from services.tts_service import tts_service
from services.redis_service import increment_user_usage, get_user_usage
from services.auth_service import get_current_user
from models.user import User, PlanType

router = APIRouter()

class PronunciationRequest(BaseModel):
    text: str

@router.post("/pronunciation-guide", response_model=PronunciationGuideResponse)
async def fetch_pronunciation_guide(
    request: PronunciationRequest,
    user: User = Depends(get_current_user)
):
    """
    Accepts a single word or short phrase and returns a detailed, beginner-friendly 
    pronunciation breakdown generated by Groq Llama 3.1.
    """
    if not request.text.strip():
        raise HTTPException(status_code=400, detail="Text cannot be empty")
        
    # Check usage limits for FREE users
    user_id_str = str(user.id)
    if user.plan_type == PlanType.FREE:
        daily_guides = await get_user_usage(user_id_str, "pronunciation")
        if daily_guides >= 5:
            raise HTTPException(
                status_code=403, 
                detail="Daily pronunciation guide limit reached for free plan. Upgrade to PRO for unlimited guides!"
            )

    # Optional logic: Reject extremely long sentences to save tokens since this is just for pronunciation
    if len(request.text) > 100:
        raise HTTPException(status_code=400, detail="Phrase too long. Please submit a single word or short phrase for pronunciation.")
        
    try:
        result = await get_pronunciation_guide(request.text)
        # Increment usage count
        await increment_user_usage(user_id_str, "pronunciation")
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/tts")
async def get_tts_audio(
    text: str,
    speed: float = 1.0,
    accent: str = "US",
    user: User = Depends(get_current_user)
):
    """
    Generates audio for the given text. PRO users get high-fidelity Google Cloud TTS, 
    while FREE users use the standard fallback.
    """
    if not text:
        raise HTTPException(status_code=400, detail="Text is required")

    # Limit speed to safe ranges
    speed = max(0.25, min(4.0, speed))

    audio_content = None

    # ONLY PRO users get premium Google Cloud TTS
    if user.plan_type == PlanType.PRO:
        audio_content = await tts_service.generate_speech_google(text, speed=speed, accent=accent)
    
    # Fallback if user is FREE, or if primary fails for PRO users
    if not audio_content:
        if user.plan_type == PlanType.FREE:
            # Maybe add a per-day limit for FREE TTS as well to prevent abuse?
            # For now, we allow fallback TTS to be used without numeric limits as it's 'free'.
            pass
        
        audio_content = await tts_service.generate_speech_fallback(text, speed=speed, accent=accent)
    
    if not audio_content:
        raise HTTPException(status_code=500, detail="Failed to generate audio via available TTS providers")

    return Response(content=audio_content, media_type="audio/mpeg")

